# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 08:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='card',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='card.Card'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='read_at',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('U', 'unread'), ('R', 'read')], default='U', max_length=1),
        ),
    ]
