# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdealStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('school', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('personality', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('height', models.PositiveIntegerField()),
                ('body_type', models.CharField(max_length=255)),
                ('age', models.CharField(choices=[('NP', '상관 없음'), ('4P', '4살 이상 연상'), ('1P', '1~3살 연상'), ('SA', '동갑'), ('1M', '1~3살 연하'), ('4M', '4살 이상 연하')], default='NP', max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
