# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideal_style', '0007_auto_20161021_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useridealstyle',
            name='age',
        ),
    ]
