# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20161015_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideo',
            name='thumbnail',
            field=models.FileField(default='a.jpg', upload_to='uploads/video_thumbnails/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 15, 8, 38, 56, 423327, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='photo',
            field=models.FileField(upload_to='uploads/photos/'),
        ),
        migrations.AlterField(
            model_name='uservideo',
            name='video',
            field=models.FileField(upload_to='uploads/videos/'),
        ),
    ]
