# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-15 17:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20161015_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIdealStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('school', models.CharField(max_length=255)),
                ('major', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(blank=True, max_length=255)),
                ('personality', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('height', models.PositiveIntegerField()),
                ('body_type', models.CharField(max_length=255)),
                ('birthday', models.DateField(default=datetime.datetime(2016, 10, 15, 17, 21, 12, 360654, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='active',
        ),
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 15, 17, 21, 12, 350654, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='useridealstyle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style', to=settings.AUTH_USER_MODEL),
        ),
    ]
