# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20161018_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 13, 0, 8, 265100, tzinfo=utc)),
        ),
    ]
