# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-18 14:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20161018_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2016, 10, 18, 14, 29, 4, 412924, tzinfo=utc)),
        ),
    ]
