# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20161020_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('SE', '서울'), ('KKI', '경기 - 일산'), ('KKU', '경기 - 의정부'), ('KKA', '경기 - 안양'), ('KKB', '경기 - 분당'), ('KKS', '경기 - 수원'), ('KKE', '경기 - 기타'), ('IC', '인천'), ('KW', '강원'), ('CB', '충북'), ('CN', '충남'), ('DJ', '대전'), ('KB', '경북'), ('DG', '대구'), ('KN', '경남'), ('BS', '부산'), ('US', '울산'), ('JB', '전북'), ('JN', '전남'), ('KJ', '광주'), ('JJ', '제주')], max_length=3),
        ),
    ]
