# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-10 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userprofile_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('media', models.FileField(upload_to='uploads/medias/')),
                ('thumbnail', models.FileField(blank=True, default='', upload_to='uploads/thumbnails/')),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UserPhoto',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='photo_ids',
            new_name='media_ids',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='video',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserVideo',
        ),
    ]
