# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 07:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20161110_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedia',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medias', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
