# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 07:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20161114_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermedia',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserMedia',
        ),
    ]
