# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0002_auto_20161015_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pointpolicy',
            old_name='point_description',
            new_name='policy_description',
        ),
    ]
