# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('point', '0003_auto_20161021_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointpolicy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 21, 13, 48, 13, 343104, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointpolicy',
            name='deleted_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
