# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('0', '발급'), ('1', '선택'), ('2', '좋아요'), ('8', '패스')], default='0', max_length=1),
        ),
    ]
